name: 'delivops-github-action-sam-deploy'
description: 'Sam deploy'
author: 'delivops'
branding:
  icon: 'cloud'
  color: 'pink'
inputs:
  aws_region:
    description: "AWS Region"
    required: true
    type: string
  aws_account_id:
    description: "AWS Account ID"
    required: true
    type: string    
  aws_role:
    description: 'aws role name'
    required: true  
  dockerfile_path:
    description: "Path to Dockerfile"
    required: true
    type: string
  sam_config_path:
    description: "SAM config file path"
    required: true
    type: string
  stack_name:
    description: "Stack Name"
    required: true
    type: string
  sam_template_path:
    description: "Template file path"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: "arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ inputs.aws_role}}"
        aws-region: ${{ inputs.aws_region }}

    - name: Deploy stack using SAM
      shell: bash
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ${{ github.workspace }}
      run: |
        sam deploy \
          --config-file "${{ github.workspace }}/${{ inputs.sam_config_path }}" \
          --stack-name ${{ inputs.stack_name }} \
          --config-env default \
          --template-file ${{ inputs.sam_template_path }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --region ${{ inputs.aws_region }} \
          --tags stack_name=${{ inputs.stack_name }} sam=true

    - name: Dry-deploy
      shell: bash
      if: github.event_name == 'pull_request'
      working-directory: ${{ github.workspace }}
      run: |
        sam deploy \
          --config-file "${{ github.workspace }}/${{ inputs.sam_config_path }}" \
          --stack-name ${{ inputs.stack_name }} \
          --config-env default \
          --template-file ${{ inputs.sam_template_path }} \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
          --no-execute-changeset \
          --region ${{ inputs.aws_region }} \
          --tags stack_name=${{ inputs.stack_name }} sam=true

    - name: Print deployment outputs
      shell: bash
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        aws cloudformation describe-stacks \
          --stack-name ${{ inputs.stack_name }} \
          --region ${{ inputs.aws_region }}